### ISSUE TITLE
What's the difference from Sindre awesome list?

### ISSUE THREAD

**Issue by parro-it** [bnb/awesome-awesome-nodejs#4]
The readme say

> going deeper down the rabbit hole.

How exactly do you plan to going deeper?

Thank you

**Comment by deadcoder0904** [comment]
I think it curates upon [Sindre](https://github.com/sindresorhus)'s [awesome-nodejs](https://github.com/sindresorhus/awesome-nodejs)

This list might be in terms of popularity or community adoption. While Sindre's list is upon quality of modules & not popularity.

But @bnb can tell better.

**Comment by bnb** [comment]
Yeah, it's meant to be a curation of awesome lists that are in the [master awesome list](http://awesome.re) - specifically awesome lists that are related to the various things you'll need/want to do when using Node.js.

Trying to not limit it to just things like modules, apps, and so on - but literally _everything_ that could be useful when using Node.js.

Does that make sense? 🤔

**Comment by parro-it** [comment]
> Does that make sense? 🤔

Yes, it does. I think it fill a gap between https://github.com/sindresorhus/awesome-nodejs and https://github.com/sindresorhus/awesome. Great idea!
